<a href="https://colab.research.google.com/github/nonnynon147/Bullets-And-Walls/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#reshape and view
my_torch = my_torch.reshape(2,5)
#will only work if product of passed numbers = total items in my_torch

In [3]:
#reshape if number of items is unknown
my_torch2 = torch.arange(10)
my_torch2
my_torch2 = my_torch2.reshape(2,-1) #only works if total elements # given number = 0
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch4 = my_torch3.view(2,-1) #same result! different process...
my_torch4 #-1 rule works!

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])